- ParameterKey: "VPC"
  ParameterValue: "vpc-8aefeced"
- ParameterKey: "SubnetA"
  ParameterValue: "subnet-5818f33e"
- ParameterKey: "SubnetB"
  ParameterValue: "subnet-6df91d25"
- ParameterKey: "HostedZoneId"
  ParameterValue: "Z03276602ECCECZUV6V61"
- ParameterKey: "HostedZoneName"
  ParameterValue: "fma.lab.myobdev.com"
- ParameterKey: "Subdomain"
  ParameterValue: "mario"
