# This is the name of your Github action "workflow"
name: Security Scans

on:
  # run this workflow when the pull request meets one of these triggers
  pull_request:
    types: [assigned, opened, edited, reopened] 
    
  # allows you to run the workflow by pushing a button
  workflow_dispatch: 

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
            # checkout local repo
      - uses: actions/checkout@v2
            # checkout appsec private actions repo
      - uses: actions/checkout@v2
        with:
          repository: myob-ops/github-actions
          ref: main
          token: ${{ secrets.APPSEC_ACTIONS_TOKEN }} # stored in GitHub secrets
          path: .github/actions
        
      - name: Trufflehog Actions Scan
        uses: ./.github/actions/trufflehog