name: Security Scans

on: push

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: $$$$$$$/github-actions
          ref: main
          token: ${{ secrets.APPSEC_ACTIONS_TOKEN }}
          path: .github/actions
        
      - name: Trufflehog Actions Scan
        uses: ./.github/actions/trufflehog